#!/usr/bin/env bash
# provision_server.sh – Idempotent Alpine NFS server provisioner.
# Called by Vagrantfile with args: <server_name> <ssh_pub_key>
# Safe to re-run without errors.

set -euo pipefail

SERVER_NAME="${1:?Usage: provision_server.sh <nfs1|nfs2> <ssh_pub_key>}"
SSH_PUB_KEY="${2:-}"

echo "==> [${SERVER_NAME}] Starting provisioning ..."

# ── 1. Package installation ──────────────────────────────────────────────────
echo "==> [${SERVER_NAME}] Updating apk and installing packages ..."
apk update -q
apk add --no-progress nfs-utils bash shadow sudo

# ── 2. Create devuser ────────────────────────────────────────────────────────
echo "==> [${SERVER_NAME}] Creating devuser account ..."
if ! id devuser &>/dev/null; then
  useradd -m -s /bin/bash devuser
fi
echo "devuser:devpass123" | chpasswd

# Passwordless sudo
if ! grep -q "^devuser" /etc/sudoers 2>/dev/null; then
  echo "devuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
fi

# ── 3. Install SSH public key for devuser ────────────────────────────────────
if [ -n "${SSH_PUB_KEY}" ]; then
  echo "==> [${SERVER_NAME}] Installing SSH public key for devuser ..."
  SSH_AUTH_DIR="/home/devuser/.ssh"
  mkdir -p "${SSH_AUTH_DIR}"
  chmod 700 "${SSH_AUTH_DIR}"
  echo "${SSH_PUB_KEY}" > "${SSH_AUTH_DIR}/authorized_keys"
  chmod 600 "${SSH_AUTH_DIR}/authorized_keys"
  chown -R devuser:devuser "${SSH_AUTH_DIR}"
fi

# ── 4. Generate share directory tree ─────────────────────────────────────────
# generate_shares.sh is uploaded by the Vagrantfile file provisioner to /tmp/nfs-lab-scripts/
echo "==> [${SERVER_NAME}] Generating share directories ..."
bash /tmp/nfs-lab-scripts/generate_shares.sh "${SERVER_NAME}"

# ── 5. Write /etc/exports ─────────────────────────────────────────────────────
echo "==> [${SERVER_NAME}] Writing /etc/exports ..."
{
  echo "# Auto-generated by provision_server.sh for ${SERVER_NAME}"
  for dir in /exports/*/; do
    [ -d "${dir}" ] || continue
    share_path="${dir%/}"
    echo "${share_path} 192.168.56.0/24(rw,sync,no_subtree_check,no_root_squash)"
  done
} > /etc/exports

echo "==> [${SERVER_NAME}] /etc/exports contents:"
cat /etc/exports

# ── 6. Enable and start NFS services via OpenRC ──────────────────────────────
echo "==> [${SERVER_NAME}] Starting NFS services ..."
rc-update add rpcbind default 2>/dev/null || true
rc-update add nfs default 2>/dev/null || true

# Start services (idempotent – rc-service handles already-running)
rc-service rpcbind start 2>/dev/null || rc-service rpcbind restart
rc-service nfs start 2>/dev/null || rc-service nfs restart

# ── 7. Reload export table ───────────────────────────────────────────────────
echo "==> [${SERVER_NAME}] Reloading exports with exportfs -ra ..."
exportfs -ra

# ── 8. Remove NAT default route (keep host-only network only) ────────────────
echo "==> [${SERVER_NAME}] Removing NAT default route ..."
ip route del default 2>/dev/null || true

echo "==> [${SERVER_NAME}] Provisioning complete."
